sudo: required
language: node_js
addons:
  chrome: stable
node_js:
- node
branches:
  except:
  - gh-pages
before_script:
- npm install -g @angular/cli
script:
- npm run travis-test
after_success:
- ng build --prod
- ci/publish_docker.sh
env:
  global:
  - COMMIT=${TRAVIS_COMMIT::8}
  - secure: Z4oSQcKbhfZofRnCNoZ829NPOYBstu6MU1SFnzo1o/echOY/bBVJ81hqHtNmQrlq0UU0scRqBSzjerBsJEunRejVmuiirG6aI/meqBxQ0fNPoYUECt1uUYOFng03ys7zhWeP/YbZfJs7p22sHFqccpqkfWCrGioPbHw4QFMmYbMoZc++TSiEA/pnj2dRRYzxenNJPGaOtq834kaRO01a3VKNvYQmjrTPIUJH7LYn0U7IuFFH1FG5EE7XWco1USWnjHRAhEfAfxSksobacGC8guJ2FZsZGsUGAtEofsYYttpb75Gyei9dKWB+RObmtNWqyRcUduoRfxSszfPRIjHHrkEcB14EV37BVhkwG2a/hSHqxJgrS8XfGKIVt1xp1CTNXCdf+yiqzvKXW5vWPxxJpAOlyaaNoi/0594U1cwz0JggwKSNWu6KLonDdwfKeYnokbCkulFOkFQkVlTn80wkMuVL6HyWGfdYEV5WpqNdxtJl0+EjXFD2mU6S/J41BZOB0bJf4qV/4FFg9u/E0M5EHcvkJj6Q/Bk8Xjb0FI++r0D9E0u1i9oVCWWOonBxMAr1ELU4hfEV3PSp0BKznfyyaKQqWWfgVefSkxzpIfEHbmDzgjfI8BH20crKXavU9BJo4OYhurYIwATrc4DgLXDLBjF/JntpHS1So8gVdesD7ak=
  - secure: uckxJifhN4x0pyL+NCrtHPhmHAleIQEFFKqU9P8Ho2BXjlcCX2PBeEX8Qmyy2C3R8BZU1YPEG3Wb7CE/+cFe2ZUzqsahd0+lkAhNAJVccOYY/x2QUVVT4oJ6r8M3rrPDUR6kAPK1vD7kd5V0LQlU33OJT4Pg6G3bGYZcsF/n8XNNGZH++1b013m7Ar04bj1txhr7T60QDhyW2f3SurxGrBU4qgWlUqrrWf404I01t0hDoH/6mK9+JQbbW/4Osk8xJDhMs4KU0FuyVUwb1kj9PE/demr4+QDf5HgbPbwQkPvCdKe+B213MlYwEISJBFmC9h6+ZLAqyEqB49pDKxx6sKmaNmFhjeVtPKbkGxhwTtJDhv9y6R2/2WV4i5i++DwVfeBAIE1qAQ/5ftC6JgD/N5q4tRthCs2LIk/OcjtHdOPXz6aR+aqI/rIl0xP4gmTou0HmbTU+/1NVTTVt7I/rHwNlJ3P+RZr61mNTVXR0PrUkAUMNX+sJAn2ozafebwQV45rDxJqrAQP+EDt+0VS4gNMquNVWG4lAoNb57w6xTGy4ypgCe0nWLD8y9q0SlFFDrql3UaFnnpFrIQFTnbmKkJGho9OaVQZFpgV5RhHGOODCmTRN8/Jx3ICjjnoP3v8hgudHjmr/FFViTfEX+Z6deS5BoOadYmfNkwAkTxnCDTM=
notifications:
  slack:
    secure: gWSmljyzKdhEySNUMS/slujuYT05r36Y20U2vL0HkIIiMC9ZUtNfUdGFBeEJVta/KK5CrPkgT6oqqQnK8h+m6AB+1Fej+zRPGGePH4v9q170QvhC3XrhrKn5ylyY9HGAwHHuGVfO3GeG9WAmFlz6dDjrhs4YkI/jPCObX+iAER9otdi7+p+u9BSKasxLoiX1C1Jm4WbSwITd1J+Enz/vpPKpCeRxUQoopEQ+rIAQi0pHUC8yVvTLAVQViRD7OEw7t955bQeBtMdAvSg6evIAXfrpFz3OjieeQ+gsvSd+gTiF7G7TJL+5F+UZaSI4Z8bmHL/Re3ryF9QSrmUL238cNwXTaOrH4EVUulKMnf5f0/Nac6eTOuNuyRXHGPZgJ09ILQzR5wu8bO+WP+OU+EqIn6frFQMZ8m/oTE5mFiqHrkJxxWt/sYVGL3Zcyjwet8BTAYGcN9gzljV8hO2mKdSntvNDNWJbdzO1YqmZFy0TPygOyBBkcsZTZInkWNMBlZMXOw2Ffigfcho9DYAEUgf/rpNvEsPNFSumbOjQZgCR1yHweNBRnD/RkNj6T7T2BUecwVZ0HstmwOG0QCEaigH+21uFKBoa4SgPkFOtSHvFUmxosmdv3uu/nOaIojsCS3Bp0sW0/0NRiw9/Gv30vf6czV75cYw5i5cyNbw8whxCgQk=
