/**
 * Cloudiator REST Api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.2.0
 * Contact: daniel.baur@uni-ulm.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { DataSinkConfiguration } from './dataSinkConfiguration';


/**
 *  Data Sink where the monitoring data will be reported to. 
 */
export interface DataSink { 
    type?: DataSink.TypeEnum;
    configuration?: Array<DataSinkConfiguration>;
}
export namespace DataSink {
    export type TypeEnum = 'KAIROS_DB' | 'INFLUX';
    export const TypeEnum = {
        KAIROSDB: 'KAIROS_DB' as TypeEnum,
        INFLUX: 'INFLUX' as TypeEnum
    };
}
