/**
 * Cloudiator REST Api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.2.0
 * Contact: daniel.baur@uni-ulm.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Location } from './location';


/**
 *  Represents a hardware offer by a cloud 
 */
export interface Hardware { 
    /**
     * Unique identifier for the hardware
     */
    id: string;
    /**
     * Human-readable name for the hardware
     */
    name: string;
    /**
     * Original id issued by the provider
     */
    providerId: string;
    /**
     * Number of cores
     */
    cores: number;
    /**
     * Amount of RAM (in MB)
     */
    ram: number;
    /**
     * Amount of disk space (in GB)
     */
    disk?: number;
    location?: Location;
}
