/**
 * Cloudiator REST Api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.2.0
 * Contact: daniel.baur@uni-ulm.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Location } from './location';
import { OperatingSystem } from './operatingSystem';


/**
 *  Represents an image offer by a cloud 
 */
export interface Image { 
    /**
     * Unique identifier for this image
     */
    id: string;
    /**
     * Human-readable name
     */
    name: string;
    /**
     * Original id issued by provider
     */
    providerId: string;
    operatingSystem: OperatingSystem;
    location?: Location;
}
