/**
 * Cloudiator REST Api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.2.0
 * Contact: daniel.baur@uni-ulm.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * A time interval consisting of unit and period
 */
export interface Interval { 
    /**
     * The unit of the interval
     */
    unit?: Interval.UnitEnum;
    /**
     * The period of the interval
     */
    period?: number;
}
export namespace Interval {
    export type UnitEnum = 'DAYS' | 'HOURS' | 'MICROSECONDS' | 'MILLISECONDS' | 'MINUTES' | 'NANOSECONDS' | 'SECONDS';
    export const UnitEnum = {
        DAYS: 'DAYS' as UnitEnum,
        HOURS: 'HOURS' as UnitEnum,
        MICROSECONDS: 'MICROSECONDS' as UnitEnum,
        MILLISECONDS: 'MILLISECONDS' as UnitEnum,
        MINUTES: 'MINUTES' as UnitEnum,
        NANOSECONDS: 'NANOSECONDS' as UnitEnum,
        SECONDS: 'SECONDS' as UnitEnum
    };
}
