/**
 * Cloudiator REST Api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.2.0
 * Contact: daniel.baur@uni-ulm.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 *  Credentials for remote access to the virtual machine. Typically, one of password or privateKey  is set. 
 */
export interface LoginCredential { 
    /**
     * The username for login
     */
    username?: string;
    /**
     * The password for login
     */
    password?: string;
    /**
     * The private key for login
     */
    privateKey?: string;
}
