/**
 * Cloudiator REST Api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.2.0
 * Contact: daniel.baur@uni-ulm.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface MonitoringTarget { 
    /**
     * target to be monitored
     */
    type: MonitoringTarget.TypeEnum;
    /**
     * identifier of a specific instance of the above type
     */
    identifier?: string;
}
export namespace MonitoringTarget {
    export type TypeEnum = 'JOB' | 'TASK' | 'PROCESS' | 'CLOUD' | 'NODE';
    export const TypeEnum = {
        JOB: 'JOB' as TypeEnum,
        TASK: 'TASK' as TypeEnum,
        PROCESS: 'PROCESS' as TypeEnum,
        CLOUD: 'CLOUD' as TypeEnum,
        NODE: 'NODE' as TypeEnum
    };
}
