/**
 * Cloudiator REST Api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.2.0
 * Contact: daniel.baur@uni-ulm.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Platform } from './platform';
import { PlatformHardware } from './platformHardware';
import { PlatformRuntime } from './platformRuntime';
import { PlatformService } from './platformService';


/**
 *  Repesents a PaaS environemnt to run an component 
 */
export interface NewPlatformEnvironment { 
    /**
     * Human-readable name
     */
    name: string;
    platform?: Platform;
    platformHardware: PlatformHardware;
    platformRuntime: PlatformRuntime;
    platformService?: Array<PlatformService>;
}
