/**
 * Cloudiator REST Api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.2.0
 * Contact: daniel.baur@uni-ulm.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * Represents a runtime for a Platform component, e.g. Java, PHP, Tomcat
 */
export interface NewPlatformRuntime { 
    /**
     * human readable name
     */
    name: string;
    /**
     * the specific runtime language
     */
    language: NewPlatformRuntime.LanguageEnum;
    /**
     * language version number
     */
    languageVersion?: number;
    /**
     * specifies the runtime type
     */
    runtimeType: NewPlatformRuntime.RuntimeTypeEnum;
    /**
     * the version of the specified type
     */
    version: number;
}
export namespace NewPlatformRuntime {
    export type LanguageEnum = 'PHP' | 'JAVA' | 'RUBY' | 'PYTHON';
    export const LanguageEnum = {
        PHP: 'PHP' as LanguageEnum,
        JAVA: 'JAVA' as LanguageEnum,
        RUBY: 'RUBY' as LanguageEnum,
        PYTHON: 'PYTHON' as LanguageEnum
    };
    export type RuntimeTypeEnum = 'standalone' | 'server';
    export const RuntimeTypeEnum = {
        Standalone: 'standalone' as RuntimeTypeEnum,
        Server: 'server' as RuntimeTypeEnum
    };
}
