/**
 * Cloudiator REST Api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.2.0
 * Contact: daniel.baur@uni-ulm.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Api } from './api';
import { CloudCredential } from './cloudCredential';


/**
 *  Repesents a new PaaS provider to be created 
 */
export interface NewPlatform { 
    /**
     * Human-readable name
     */
    name: string;
    /**
     * PaaS stack type
     */
    type?: NewPlatform.TypeEnum;
    api: Api;
    credential: CloudCredential;
    /**
     * URI where the api of this platform provider can be accessed.
     */
    endpoint?: string;
}
export namespace NewPlatform {
    export type TypeEnum = 'HEROKU' | 'OPENSHIFT' | 'CLOUDFOUNDRY';
    export const TypeEnum = {
        HEROKU: 'HEROKU' as TypeEnum,
        OPENSHIFT: 'OPENSHIFT' as TypeEnum,
        CLOUDFOUNDRY: 'CLOUDFOUNDRY' as TypeEnum
    };
}
