/**
 * Cloudiator REST Api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.2.0
 * Contact: daniel.baur@uni-ulm.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { GeoLocation } from './geoLocation';
import { OperatingSystem } from './operatingSystem';


/**
 * attributes defining a node
 */
export interface NodeProperties { 
    numberOfCores?: number;
    memory?: number;
    disk?: number;
    operatingSystem?: OperatingSystem;
    geoLocation?: GeoLocation;
}
