/**
 * Cloudiator REST Api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.2.0
 * Contact: daniel.baur@uni-ulm.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { IpAddress } from './ipAddress';
import { LoginCredential } from './loginCredential';
import { NodeProperties } from './nodeProperties';


export interface Node { 
    nodeId?: string;
    loginCredential?: LoginCredential;
    nodeType?: Node.NodeTypeEnum;
    ipAddresses?: Array<IpAddress>;
    nodeProperties?: NodeProperties;
}
export namespace Node {
    export type NodeTypeEnum = 'UNKNOWN_TYPE' | 'VM' | 'BYON' | 'CONTAINER';
    export const NodeTypeEnum = {
        UNKNOWNTYPE: 'UNKNOWN_TYPE' as NodeTypeEnum,
        VM: 'VM' as NodeTypeEnum,
        BYON: 'BYON' as NodeTypeEnum,
        CONTAINER: 'CONTAINER' as NodeTypeEnum
    };
}
