/**
 * Cloudiator REST Api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.2.0
 * Contact: daniel.baur@uni-ulm.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Requirement } from './requirement';


/**
 *  Array of Requirements.  Represents a request to create a new node fullfilling the given requirements 
 */
export interface NodeRequirements { 
    requirements?: Array<Requirement>;
}
