/**
 * Cloudiator REST Api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.2.0
 * Contact: daniel.baur@uni-ulm.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * OS Type
 */
export type OperatingSystemType = 'LINUX' | 'UNKOWN' | 'UNIX' | 'WINDOWS_OS' | 'BSD' | 'MAC';

export const OperatingSystemType = {
    LINUX: 'LINUX' as OperatingSystemType,
    UNKOWN: 'UNKOWN' as OperatingSystemType,
    UNIX: 'UNIX' as OperatingSystemType,
    WINDOWSOS: 'WINDOWS_OS' as OperatingSystemType,
    BSD: 'BSD' as OperatingSystemType,
    MAC: 'MAC' as OperatingSystemType
};
