/**
 * Cloudiator REST Api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.2.0
 * Contact: daniel.baur@uni-ulm.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { OperatingSystemArchitecture } from './operatingSystemArchitecture';
import { OperatingSystemFamily } from './operatingSystemFamily';
import { OperatingSystemType } from './operatingSystemType';


/**
 *  Represents the operating system of an image 
 */
export interface OperatingSystem { 
    operatingSystemType?: OperatingSystemType;
    operatingSystemFamily?: OperatingSystemFamily;
    operatingSystemArchitecture?: OperatingSystemArchitecture;
    /**
     * Version of the OS
     */
    operatingSystemVersion?: string;
}
