/**
 * Cloudiator REST Api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.2.0
 * Contact: daniel.baur@uni-ulm.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * Type of OS Architecture
 */
export type OperatingSystemArchitecture = 'AMD64' | 'UNKOWN' | 'I386';

export const OperatingSystemArchitecture = {
    AMD64: 'AMD64' as OperatingSystemArchitecture,
    UNKOWN: 'UNKOWN' as OperatingSystemArchitecture,
    I386: 'I386' as OperatingSystemArchitecture
};
