/**
 * Cloudiator REST Api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.2.0
 * Contact: daniel.baur@uni-ulm.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * Type of OS Family
 */
export type OperatingSystemFamily = 'UBUNTU' | 'UNKOWN_OS_FAMILY' | 'AIX' | 'ARCH' | 'CENTOS' | 'DARWIN' | 'DEBIAN' | 'ESX' | 'FEDORA' | 'FREEBSD' | 'GENTOO' | 'HPUX' | 'COREOS' | 'AMZN_LINUX' | 'MANDRIVA' | 'NETBSD' | 'OEL' | 'OPENBSD' | 'RHEL' | 'SCIENTIFIC' | 'CEL' | 'SLACKWARE' | 'SOLARIS' | 'SUSE' | 'TURBOLINUX' | 'CLOUD_LINUX' | 'WINDOWS';

export const OperatingSystemFamily = {
    UBUNTU: 'UBUNTU' as OperatingSystemFamily,
    UNKOWNOSFAMILY: 'UNKOWN_OS_FAMILY' as OperatingSystemFamily,
    AIX: 'AIX' as OperatingSystemFamily,
    ARCH: 'ARCH' as OperatingSystemFamily,
    CENTOS: 'CENTOS' as OperatingSystemFamily,
    DARWIN: 'DARWIN' as OperatingSystemFamily,
    DEBIAN: 'DEBIAN' as OperatingSystemFamily,
    ESX: 'ESX' as OperatingSystemFamily,
    FEDORA: 'FEDORA' as OperatingSystemFamily,
    FREEBSD: 'FREEBSD' as OperatingSystemFamily,
    GENTOO: 'GENTOO' as OperatingSystemFamily,
    HPUX: 'HPUX' as OperatingSystemFamily,
    COREOS: 'COREOS' as OperatingSystemFamily,
    AMZNLINUX: 'AMZN_LINUX' as OperatingSystemFamily,
    MANDRIVA: 'MANDRIVA' as OperatingSystemFamily,
    NETBSD: 'NETBSD' as OperatingSystemFamily,
    OEL: 'OEL' as OperatingSystemFamily,
    OPENBSD: 'OPENBSD' as OperatingSystemFamily,
    RHEL: 'RHEL' as OperatingSystemFamily,
    SCIENTIFIC: 'SCIENTIFIC' as OperatingSystemFamily,
    CEL: 'CEL' as OperatingSystemFamily,
    SLACKWARE: 'SLACKWARE' as OperatingSystemFamily,
    SOLARIS: 'SOLARIS' as OperatingSystemFamily,
    SUSE: 'SUSE' as OperatingSystemFamily,
    TURBOLINUX: 'TURBOLINUX' as OperatingSystemFamily,
    CLOUDLINUX: 'CLOUD_LINUX' as OperatingSystemFamily,
    WINDOWS: 'WINDOWS' as OperatingSystemFamily
};
