/**
 * Cloudiator REST Api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.2.0
 * Contact: daniel.baur@uni-ulm.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { NewPlatformHardware } from './newPlatformHardware';


/**
 *  Repesents a PaaS environemnt to run an component 
 */
export interface PlatformHardware { 
    /**
     * Human-readable name for the hardware
     */
    name: string;
    /**
     * Number of cores
     */
    cores: number;
    /**
     * Amount of RAM
     */
    ram: number;
    /**
     * Amount of disk space
     */
    disk: number;
    /**
     * Unique identifier for the hardware
     */
    id?: string;
}
