/**
 * Cloudiator REST Api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.2.0
 * Contact: daniel.baur@uni-ulm.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Api } from './api';
import { CloudCredential } from './cloudCredential';
import { NewPlatform } from './newPlatform';


/**
 * Representation of a platform used by Cloudiator
 */
export interface Platform { 
    /**
     * Human-readable name
     */
    name: string;
    /**
     * PaaS stack type
     */
    type?: Platform.TypeEnum;
    api: Api;
    credential: CloudCredential;
    /**
     * URI where the api of this platform provider can be accessed.
     */
    endpoint?: string;
    /**
     * Unique identifier for the platform
     */
    id?: string;
}
export namespace Platform {
    export type TypeEnum = 'HEROKU' | 'OPENSHIFT' | 'CLOUDFOUNDRY';
    export const TypeEnum = {
        HEROKU: 'HEROKU' as TypeEnum,
        OPENSHIFT: 'OPENSHIFT' as TypeEnum,
        CLOUDFOUNDRY: 'CLOUDFOUNDRY' as TypeEnum
    };
}
