/**
 * Cloudiator REST Api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.2.0
 * Contact: daniel.baur@uni-ulm.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Port } from './port';


/**
 *  Subtype of port.  Represents a communication port that the tasks provides for other tasks  or the end user. 
 */
export interface PortProvided extends Port { 
    port: number;
}
