/**
 * Cloudiator REST Api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.2.0
 * Contact: daniel.baur@uni-ulm.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Port } from './port';


/**
 *  Subtype of port.  Represents a communication port that the task requires from other (downstream) tasks. 
 */
export interface PortRequired extends Port { 
    /**
     *  A script that is executed if a new instance of a downstream task is available. 
     */
    updateAction?: string;
    /**
     *  States if an instance of a downstream tasks needs to be already started (true), or  if the task can start without a downstream task (false). 
     */
    isMandatory: boolean;
}
