/**
 * Cloudiator REST Api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.2.0
 * Contact: daniel.baur@uni-ulm.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Interval } from './interval';
import { Sensor } from './sensor';
import { SensorConfiguration } from './sensorConfiguration';


export interface PullSensor extends Sensor { 
    /**
     * ClassName of the sensor
     */
    className?: string;
    /**
     * Configuration of the sensor
     */
    configuration?: SensorConfiguration;
    /**
     * The interval at which the sensor is executed
     */
    interval?: Interval;
}
