/**
 * Cloudiator REST Api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.2.0
 * Contact: daniel.baur@uni-ulm.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 *  Status of the running task 
 */
export type QueueStatus = 'SCHEDULED' | 'RUNNING' | 'COMPLETED' | 'FAILED';

export const QueueStatus = {
    SCHEDULED: 'SCHEDULED' as QueueStatus,
    RUNNING: 'RUNNING' as QueueStatus,
    COMPLETED: 'COMPLETED' as QueueStatus,
    FAILED: 'FAILED' as QueueStatus
};
