/**
 * Cloudiator REST Api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.2.0
 * Contact: daniel.baur@uni-ulm.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * Part of AttributeRequirement
 */
export type RequirementOperator = 'EQ' | 'LEQ' | 'GEQ' | 'GT' | 'LT' | 'NEQ' | 'IN';

export const RequirementOperator = {
    EQ: 'EQ' as RequirementOperator,
    LEQ: 'LEQ' as RequirementOperator,
    GEQ: 'GEQ' as RequirementOperator,
    GT: 'GT' as RequirementOperator,
    LT: 'LT' as RequirementOperator,
    NEQ: 'NEQ' as RequirementOperator,
    IN: 'IN' as RequirementOperator
};
