/**
 * Cloudiator REST Api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.2.0
 * Contact: daniel.baur@uni-ulm.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ScheduleNew } from './scheduleNew';


export interface Schedule { 
    /**
     * The identifier of the job
     */
    job?: string;
    /**
     * If the instantiation should be handled AUTOMATIC or MANUAL
     */
    instantiation?: Schedule.InstantiationEnum;
    id?: string;
}
export namespace Schedule {
    export type InstantiationEnum = 'AUTOMATIC' | 'MANUAL';
    export const InstantiationEnum = {
        AUTOMATIC: 'AUTOMATIC' as InstantiationEnum,
        MANUAL: 'MANUAL' as InstantiationEnum
    };
}
