/**
 * Cloudiator REST Api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.2.0
 * Contact: daniel.baur@uni-ulm.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Property } from './property';


/**
 * Key-Value configuration of the sensor
 */
export interface SensorConfiguration { 
    /**
     * Array of configuration properties
     */
    properties?: Array<Property>;
}
