/**
 * Cloudiator REST Api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.2.0
 * Contact: daniel.baur@uni-ulm.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ExecutionEnvironment } from './executionEnvironment';
import { Optimization } from './optimization';
import { Port } from './port';
import { Requirement } from './requirement';
import { TaskInterface } from './taskInterface';
import { TaskType } from './taskType';


/**
 *  Represents a new task of a job. 
 */
export interface Task { 
    /**
     * Human-readable name. Uniquely identifies a task.
     */
    name: string;
    ports?: Array<Port>;
    /**
     * Interfaces of this task
     */
    interfaces?: Array<TaskInterface>;
    executionEnvironment: ExecutionEnvironment;
    optimization?: Optimization;
    requirements?: Array<Requirement>;
    taskType: TaskType;
}
