/**
 * Cloudiator REST Api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.2.0
 * Contact: daniel.baur@uni-ulm.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * a Cloudiator tool to be installed on a node
 */
export type Tool = 'DOCKER' | 'KAIROSDB' | 'LANCE' | 'VISOR' | 'AXE';

export const Tool = {
    DOCKER: 'DOCKER' as Tool,
    KAIROSDB: 'KAIROSDB' as Tool,
    LANCE: 'LANCE' as Tool,
    VISOR: 'VISOR' as Tool,
    AXE: 'AXE' as Tool
};
