/**
 * Cloudiator REST Api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.2.0
 * Contact: daniel.baur@uni-ulm.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Hardware } from './hardware';
import { Image } from './image';
import { IpAddress } from './ipAddress';
import { Location } from './location';
import { LoginCredential } from './loginCredential';


export interface VirtualMachine { 
    image?: Image;
    hardware?: Hardware;
    location?: Location;
    id?: string;
    ipaddresses?: Array<IpAddress>;
    logincredential?: LoginCredential;
}
